# 2. NumPy 基礎

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [3]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [18]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [19]:
m.shape

(2, 2)

### 2.2.1 選取數組元素

In [24]:
a = np.array(range(4))
a.shape = (2, 2)
a

array([[0, 1],
       [2, 3]])

In [28]:
a[1, 0]

2

### 2.2.2 data type

In [29]:
bool(42)

True

In [30]:
bool(0)

False

In [31]:
bool(-1)

True

In [32]:
float64(42)

42.0

In [33]:
a = np.array(range(4))
a.dtype

dtype('int64')

In [34]:
a.dtype.itemsize

8

In [35]:
np.arange(7,  dtype = 'f')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.], dtype=float32)

In [36]:
np.arange(7, dtype = 'D')

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j])

### 2.2.5 自定義數據類型

In [37]:
dtype(float)

dtype('float64')

In [38]:
dtype('f')

dtype('float32')

In [39]:
dtype('d')

dtype('float64')

In [40]:
# 自定義 類型+byte數
dtype('f4')

dtype('float32')

In [48]:
sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'float128', 'Float128', 'f16', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'complex256', 'Complex128', 'c32', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int64', 'uint64', 'Int64', 'UInt64', 'i8', 'u8', 'int32', 'uint32', 'Int32', 'UInt32', 'i4', 'u4', 'int16', 'uint16', 'Int16', 'UInt16', 'i2', 'u2', 'int8', 'uint8', 'Int8', 'UInt8', 'i1', 'u1', 'complex_',

### 2.2.6 dtype 的屬性

In [52]:
t = dtype('Float32')
t.char

'f'

In [54]:
dtype('f')

dtype('float32')

In [55]:
t.str

'<f4'

In [56]:
dtype('<f4')

dtype('float32')

In [59]:
dtype('>f4')

dtype('>f4')

## 2.3 自定義數據類型

In [61]:
t = dtype([('name', str_, 40), ('numitems',  int32), ('price', float32)])
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [62]:
t['name']

dtype('<U40')

In [64]:
itemz = array([('Meaning of live DVD',  42,  3.14), ('Butter', 12,  2.72)],  dtype = t)
itemz

array([('Meaning of live DVD', 42, 3.140000104904175),
       ('Butter', 12, 2.7200000286102295)], 
      dtype=[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

## 2.4 索引與切片

In [65]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [66]:
a[:7:2]

array([0, 2, 4, 6])

In [67]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2.5 多維數組的索引與切片

In [71]:
b = arange(24).reshape((2, 3, 4))
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [72]:
b.shape

(2, 3, 4)

In [73]:
b[:,0, 0]

array([ 0, 12])

In [74]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
b[0, 1]

array([4, 5, 6, 7])

In [78]:
b[0, 1, ::2]

array([4, 6])

In [79]:
b[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [80]:
b[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [82]:
b[0, :, -1]

array([ 3,  7, 11])

In [83]:
b[0, ::-1, -1]

array([11,  7,  3])

In [84]:
b[0, ::2, -1]

array([ 3, 11])

In [85]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## 2.6 改變數組的維度

In [88]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [89]:
# 展平
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [90]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [92]:
b.shape = (6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [96]:
# resize 是 inplace 的 funciton
b.resize((2, 12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

## 2.7 數組的組合

In [97]:
a = arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [100]:
hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [101]:
concatenate((a, b), axis = 1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [102]:
vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [103]:
concatenate((a, b), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [104]:
dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [105]:
oned = arange(2)
oned

array([0, 1])

In [106]:
twice_oned = 2 * oned
twice_oned

array([0, 2])

In [108]:
# 從每列中抽取同一個 column 的元素 組成一個 array
column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [109]:
# 對於 2維數組來說， column_stack 和 hstack 的效果相同
column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [110]:
hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [111]:
column_stack((a, b)) == hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

In [112]:
# 從每行中抽取同一個 row的元素 組成一個 array
row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [114]:
row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [115]:
vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [116]:
# 對於 2維數組來說， row_stack 和 vstack 的效果相同
row_stack((a, b)) == vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## 2.10 的分割

In [118]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [121]:
split(a, 3, axis = 1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [122]:
vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [123]:
split(a, 3, axis = 0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [125]:
c = arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

## 2.11 數組的屬性

In [127]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [128]:
b.ndim

2

In [129]:
b.size

9

In [131]:
b.dtype

dtype('int64')

In [130]:
b.itemsize

8

In [134]:
b.size * b.itemsize

72

In [132]:
b.nbytes

72

In [135]:
b.transpose()

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

In [136]:
np.transpose(b)

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

In [137]:
b.T

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

In [139]:
b = array([1.j +1, 2.j +3])
b

array([ 1.+1.j,  3.+2.j])

In [140]:
real(b)

array([ 1.,  3.])

In [141]:
imag(b)

array([ 1.,  2.])

In [142]:
b.dtype

dtype('complex128')

In [143]:
b.dtype.str

'<c16'

In [144]:
b = arange(4).reshape(2, 2)
b

array([[0, 1],
       [2, 3]])

In [145]:
# flat: 扁平 iterator
f = b.flat
f

In [146]:
for item in f:
    print(item)

0
1
2
3


In [147]:
# 用 扁平 iterator 賦值
b.flat = 7
b

array([[7, 7],
       [7, 7]])

## 2.12 數組的轉換


In [148]:
b = arange(24).reshape(4, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [149]:
b.tolist()

[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [150]:
b.dtype

dtype('int64')

In [155]:
# 型態轉換
b.astype(int32).dtype

dtype('int32')

In [156]:
b.astype('complex').dtype

dtype('complex128')